# Generated by Django 2.2 on 2020-02-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('as_a', 'AS A'), ('Customer', 'CUSTOMER'), ('Service_Provider', 'SERVICES PROVIDER')], default='as_a', max_length=15),
        ),
    ]
