# Generated by Django 2.2 on 2020-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'CUSTOMER'), ('Service_Provider', 'SERVICES PROVIDER')], default='Customer', max_length=15),
        ),
    ]
