# Generated by Django 2.2 on 2020-02-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_comment_servicerequest_services_servicesprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesprovider',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
    ]
