# Generated by Django 2.2 on 2020-02-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200216_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='user_type',
            new_name='status',
        ),
    ]
