# Generated by Django 2.2 on 2020-02-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200216_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='service',
        ),
        migrations.AddField(
            model_name='comment',
            name='ServiceRequest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.ServiceRequest'),
            preserve_default=False,
        ),
    ]
