# Generated by Django 2.2 on 2020-02-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200217_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ServiceRequest',
            new_name='servicerequest',
        ),
    ]
