# Generated by Django 2.2 on 2020-02-17 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200217_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesprovider',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('0', 'PENDING'), ('1', 'ACCEPT'), ('2', 'REJECT'), ('3', 'COMPLETE')], default='Pending', max_length=15),
        ),
    ]
