# Generated by Django 2.2 on 2020-02-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200217_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Accept', 'ACCEPT'), ('Reject', 'REJECT'), ('Complete', 'COMPLETE')], default='Pending', max_length=15),
        ),
    ]
